
spring:
  application:
    name: healthy-dining

  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}-${random.int(1,99)}
        register-health-check: true
        health-check-timeout: 10s
        health-check-interval: 5s
        health-check-critical-timeout: 10s
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8099/auth/realms/vrsa"
server:
  port: 7001

management:
  endpoints:
    web:
      exposure:
        include: '*'